export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURNED: 'RETURNED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  AWAITING: 'AWAITING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
};

export const STATUS_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [
    ORDER_STATUSES.CONFIRMED,
    ORDER_STATUSES.CANCELLED,
    ORDER_STATUSES.FAILED,
  ],
  [ORDER_STATUSES.CONFIRMED]: [
    ORDER_STATUSES.PROCESSING,
    ORDER_STATUSES.CANCELLED,
  ],
  [ORDER_STATUSES.PROCESSING]: [
    ORDER_STATUSES.SHIPPED,
    ORDER_STATUSES.CANCELLED,
  ],
  [ORDER_STATUSES.SHIPPED]: [
    ORDER_STATUSES.OUT_FOR_DELIVERY,
    ORDER_STATUSES.RETURN_REQUESTED,
  ],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [
    ORDER_STATUSES.DELIVERED,
    ORDER_STATUSES.RETURN_REQUESTED,
  ],
  [ORDER_STATUSES.DELIVERED]: [
    ORDER_STATUSES.RETURN_REQUESTED,
    ORDER_STATUSES.REFUNDED,
  ],
  [ORDER_STATUSES.CANCELLED]: [],
  [ORDER_STATUSES.RETURN_REQUESTED]: [
    ORDER_STATUSES.RETURNED,
  ],
  [ORDER_STATUSES.RETURNED]: [
    ORDER_STATUSES.REFUNDED,
  ],
  [ORDER_STATUSES.REFUNDED]: [],
  [ORDER_STATUSES.FAILED]: [
    ORDER_STATUSES.PENDING,
  ],
};

export const STATUS_COLORS = {
  [ORDER_STATUSES.PENDING]: '#F59E0B',
  [ORDER_STATUSES.CONFIRMED]: '#3B82F6',
  [ORDER_STATUSES.PROCESSING]: '#8B5CF6',
  [ORDER_STATUSES.SHIPPED]: '#6366F1',
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: '#EC4899',
  [ORDER_STATUSES.DELIVERED]: '#10B981',
  [ORDER_STATUSES.CANCELLED]: '#EF4444',
  [ORDER_STATUSES.RETURN_REQUESTED]: '#F97316',
  [ORDER_STATUSES.RETURNED]: '#6B7280',
  [ORDER_STATUSES.REFUNDED]: '#14B8A6',
  [ORDER_STATUSES.FAILED]: '#DC2626',
};
