export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  WHOLESALE: 'WHOLESALE',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
  SUPPORT_EXECUTIVE: 'SUPPORT_EXECUTIVE',
  MARKETING: 'MARKETING',
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  OWNER: 'OWNER',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const ROLE_HIERARCHY = {
  SUPER_ADMIN: 5,
  OWNER: 4,
  MANAGER: 3,
  EMPLOYEE: 2,
  WAREHOUSE_STAFF: 2,
  SUPPORT_EXECUTIVE: 2,
  MARKETING: 2,
  WHOLESALE: 1,
  CUSTOMER: 0,
};

export const DEFAULT_ROLE = ROLES.CUSTOMER;
